# Build stage
FROM node:20-alpine as build
WORKDIR /app/frontend
COPY . .
RUN npm ci
RUN npm run build

# Production stage
FROM nginx:alpine
COPY --from=build /app/frontend /usr/share/nginx/html

# Optional: overwrite default Nginx config
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
