services:
  studio:
    build:
      context: ..
      dockerfile: app/backend/Dockerfile
    ports:
      - "8000"
    volumes:
      - ./:/app
      - my_media:/app/media
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    working_dir: /app/backend

  db:
    image: postgres:16.0-alpine3.17
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - my_db:$PGDATA

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  celery:
    build:
      context: ..
      dockerfile: app/backend/Dockerfile
    command: >
      sh -c "python manage.py wait_for_db &&
             celery -A design_studio worker -l INFO"
    depends_on:
      - redis
      - db
    env_file:
      - .env
    volumes:
      - ./:/app
      - my_media:/app/media
    working_dir: /app/backend

  frontend:
    build:
      context: ..
      dockerfile: app/frontend/Dockerfile
    ports:
      - "80"
    depends_on:
      - studio
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
      - ./frontend/build:/usr/share/nginx/html
    depends_on:
      - frontend
    entrypoint: >
      sh -c "mkdir -p /var/www/certbot/.well-known/acme-challenge &&
             echo OK > /var/www/certbot/.well-known/acme-challenge/test &&
             exec nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: sh -c "certbot certonly --webroot --webroot-path=/var/www/certbot
             --email interior.design.studio.projec@gmail.com --agree-tos --no-eff-email
             -d tavrdesing.com.ua -d www.tavrdesing.com.ua"

volumes:
  my_db:
  my_media:
  certbot-etc:
  certbot-www:
  certbot-var:
