server {
    listen 80;
    server_name tavrdesing.com.ua www.tavrdesing.com.ua;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name tavrdesing.com.ua www.tavrdesing.com.ua;

    client_max_body_size 50M;

    ssl_certificate /etc/letsencrypt/live/tavrdesing.com.ua/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tavrdesing.com.ua/privkey.pem;

    # 🔁 Frontend — all requests except /api/, /admin/, /media/
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # 🔁 Backend Django
    location /api/ {
        proxy_pass http://studio:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /admin/ {
        proxy_pass http://studio:8000/admin/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /media/ {
        proxy_pass http://studio:8000/media/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /backend-static/ {
        proxy_pass http://studio:8000/backend-static/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}
